services:
  db:
    image: postgres:16
    container_name: jobtracker-postgres
    environment:
      POSTGRES_DB: jobtracker
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_pgdata:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog:latest
    container_name: jobtracker-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: jobtracker-backend
    environment:
      SERVER_PORT: "9000"
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/jobtracker
      SPRING_DATASOURCE_USERNAME: jobtracker
      SPRING_DATASOURCE_PASSWORD: jobtracker
      CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://127.0.0.1:4200,http://localhost,http://127.0.0.1"
      MAIL_HOST: mailhog
      MAIL_PORT: "1025"
      MAIL_FROM: noreply@jobtracker.local
      JWT_SECRET: "Good-luck-with-your-job-hunt-and-all-the-best"
    ports:
      - "9000:9000"
    depends_on:
      - db
      - mailhog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: jobtracker-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  jobtracker_pgdata:

